name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install markdown-to-slides -g
    - run: markdown-to-slides -d README.md -o docs/slides.html
    - run: git config --global user.email "john.french@gmit.ie"
    - run: git config --global user.name "John French"
    - run: git add docs/slides.html
    - run: git commit -m "rendered slides"  
    - run: git push
      env:
        CI: true
